name: Rcpp Gallery
description: Gallery of Rcpp Examples

absoluteurl: http://gallery.rcpp.org
baseurl: /
permalink: ":year/:month/:day/:title"

exclude: Makefile, rcpp-gallery.Rproj

pygments: true


