name: Rcpp Gallery
description: Articles and code that provide examples of using the Rcpp package
repo: https://github.com/jjallaire/rcpp-gallery

url: http://gallery.rcpp.org
baseurl: /
permalink: ":year/:month/:day/:title"

exclude: 
  - README.md 
  - CONTRIBUTING.md
  - Makefile
  - rcpp-gallery.Rproj

pygments: true


